#!/usr/bin/env python

## -- Python Setup -- ##
import os.path
import sys

PROJECT_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, PROJECT_ROOT)
sys.path.insert(0, os.path.join(PROJECT_ROOT, '..'))

## -- Django Setup -- ##
import os
import django
from thialfi import settings
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "thialfi.settings")
django.setup()

## -- Here comes the script -- ##
from thialfi.logger import *
from app.models import *

for group in Group.objects.all():
	info(u"[%s]" % group.name)
	for contact in group.contacts.all():
		is_primary = (contact == group.contact_primary)
		info(u" %s %s" % (is_primary and ">" or " ", contact.name))
	if group.contact_primary not in group.contacts.all():
		warn(u"!> %s" % group.contact_primary.name)
	info("===")
