#!/bin/sh
#
# chkconfig: - 99 01
# description: Start up Thialfi's process-messages process
#
### BEGIN INIT INFO
# Provides: thialfi
# Required-Start: $remote_fs $time
# Should-Start: postfix httpd
# Should-Stop: $null
# Required-Stop: $null
# Default-Stop: 0 1 6
# Short-Description: Thialfi message processing
# Description: Start up Thialfi's process-messages process
### END INIT INFO

RETVAL=0

# Source function library.
. /etc/init.d/functions

PROG=/app/thialfi/scripts/process-messages
LOG_FILE=/var/log/thialfi-process-messages.log
PID_FILE=/var/run/thialfi.pid

case "$1" in
    start)
        ${PROG} >> ${LOG_FILE} 2>&1 &
        echo $! > ${PID_FILE}
        ;;

    stop)
        kill $(cat ${PID_FILE})
        rm -f ${PID_FILE}
        ;;

    restart)
        stop
        start
        ;;

    *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 2
esac
exit $?
